FROM golang:1.22-bookworm AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN go build -o ./tmp/main ./cmd/client/main.go

FROM golang:1.22-bookworm AS production

WORKDIR /app

COPY --from=build /app/tmp/main ./cli

RUN ./cli change_addr -a server:1234

CMD ["tail", "-f", "/dev/null"]
