FROM golang:1.22-bookworm AS build

WORKDIR /app

COPY go.mod .
COPY go.sum .

RUN go mod download

COPY . .
RUN go build -o ./tmp/main ./cmd/server/main.go

FROM golang:1.22-bookworm AS production

WORKDIR /app

RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.17.0/migrate.linux-amd64.tar.gz | tar xvz -C $(go env GOPATH)/bin

COPY --from=build /app/tmp/main ./main
COPY --from=build /app/migrations ./migrations

CMD [ "./main" ]
